/cm/local/apps/slurm/var/spool/job379070/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job379070/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job379070/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-17 15:43:48.745995: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-17 15:43:50.089867: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-17 15:43:50.090023: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-17 15:43:50.272467: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-17 15:43:50.618076: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-17 15:43:56.326348: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
working on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_normal_6_0.01_MAR_0
loading data
data/6_True.pkl
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-17 15:44:28,479] A new study created in memory with name: no-name-bb994d4c-4ba8-45ef-83f1-2992db8c49e3
[W 2023-11-17 15:44:28,480] Trial 0 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:28,487] Trial 0 failed with value None.
[W 2023-11-17 15:44:28,481] Trial 1 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:28,678] Trial 1 failed with value None.
[W 2023-11-17 15:44:28,485] Trial 4 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:28,823] Trial 4 failed with value None.
[W 2023-11-17 15:44:28,485] Trial 5 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:28,964] Trial 5 failed with value None.
[W 2023-11-17 15:44:28,486] Trial 7 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:29,107] Trial 7 failed with value None.
[W 2023-11-17 15:44:28,677] Trial 8 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:29,248] Trial 8 failed with value None.
[W 2023-11-17 15:44:28,486] Trial 6 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:29,389] Trial 6 failed with value None.
[W 2023-11-17 15:44:28,483] Trial 3 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:29,532] Trial 3 failed with value None.
[W 2023-11-17 15:44:29,532] Trial 9 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:29,673] Trial 9 failed with value None.
[W 2023-11-17 15:44:28,482] Trial 2 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:29,816] Trial 2 failed with value None.
[W 2023-11-17 15:44:29,673] Trial 10 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:29,959] Trial 10 failed with value None.
[W 2023-11-17 15:44:29,957] Trial 11 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:30,104] Trial 11 failed with value None.
[W 2023-11-17 15:44:30,101] Trial 13 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:30,247] Trial 13 failed with value None.
[W 2023-11-17 15:44:30,103] Trial 15 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:30,394] Trial 15 failed with value None.
[W 2023-11-17 15:44:30,103] Trial 16 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:30,541] Trial 16 failed with value None.
[W 2023-11-17 15:44:29,958] Trial 12 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:30,683] Trial 12 failed with value None.
[W 2023-11-17 15:44:30,106] Trial 19 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:30,826] Trial 19 failed with value None.
[W 2023-11-17 15:44:30,102] Trial 14 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:30,971] Trial 14 failed with value None.
[W 2023-11-17 15:44:30,393] Trial 22 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,117] Trial 22 failed with value None.
[W 2023-11-17 15:44:30,539] Trial 24 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,263] Trial 24 failed with value None.
[W 2023-11-17 15:44:30,539] Trial 25 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,406] Trial 25 failed with value None.
[W 2023-11-17 15:44:30,541] Trial 27 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,548] Trial 27 failed with value None.
[W 2023-11-17 15:44:30,246] Trial 20 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,689] Trial 20 failed with value None.
[W 2023-11-17 15:44:30,391] Trial 21 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,832] Trial 21 failed with value None.
[W 2023-11-17 15:44:30,970] Trial 31 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,977] Trial 31 failed with value None.
[W 2023-11-17 15:44:30,104] Trial 17 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:32,118] Trial 17 failed with value None.
[W 2023-11-17 15:44:31,112] Trial 33 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:32,261] Trial 33 failed with value None.
[W 2023-11-17 15:44:31,113] Trial 36 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:32,405] Trial 36 failed with value None.
[W 2023-11-17 15:44:31,115] Trial 38 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:32,549] Trial 38 failed with value None.
[W 2023-11-17 15:44:31,116] Trial 39 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:32,692] Trial 39 failed with value None.
[W 2023-11-17 15:44:30,538] Trial 23 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:32,834] Trial 23 failed with value None.
[W 2023-11-17 15:44:31,261] Trial 42 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:31,262] Trial 44 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:32,976] Trial 44 failed with value None.
[W 2023-11-17 15:44:31,263] Trial 45 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:33,118] Trial 45 failed with value None.
[W 2023-11-17 15:44:30,104] Trial 18 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:33,258] Trial 18 failed with value None.
[W 2023-11-17 15:44:31,547] Trial 47 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:33,399] Trial 47 failed with value None.
[W 2023-11-17 15:44:30,969] Trial 30 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:33,544] Trial 30 failed with value None.
[W 2023-11-17 15:44:31,111] Trial 32 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:33,684] Trial 32 failed with value None.
[W 2023-11-17 15:44:31,113] Trial 35 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:33,827] Trial 35 failed with value None.
[W 2023-11-17 15:44:31,117] Trial 40 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:33,967] Trial 40 failed with value None.
[W 2023-11-17 15:44:31,262] Trial 43 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:34,107] Trial 43 failed with value None.
[W 2023-11-17 15:44:30,540] Trial 26 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:34,251] Trial 26 failed with value None.
[W 2023-11-17 15:44:30,968] Trial 29 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:34,394] Trial 29 failed with value None.
[W 2023-11-17 15:44:31,112] Trial 34 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:34,538] Trial 34 failed with value None.
[W 2023-11-17 15:44:31,118] Trial 41 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:34,678] Trial 41 failed with value None.
[W 2023-11-17 15:44:30,825] Trial 28 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:34,820] Trial 28 failed with value None.
[W 2023-11-17 15:44:31,114] Trial 37 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:34,962] Trial 37 failed with value None.
[W 2023-11-17 15:44:32,976] Trial 42 failed with value None.
[W 2023-11-17 15:44:31,547] Trial 46 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:35,245] Trial 46 failed with value None.
failed on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_normal_6_0.01_MAR_0
module 'utils' has no attribute 'trial_suggestion'
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 169, in loop_through_tasks
    SimpleImputeSpace.fit(X_train_pandas)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'

DONE
