/cm/local/apps/slurm/var/spool/job379089/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job379089/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job379089/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-17 15:46:24.576489: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-17 15:46:24.611170: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-17 15:46:24.611196: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-17 15:46:24.612320: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-17 15:46:24.618056: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-17 15:46:26.204620: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
working on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_normal_6_0.1_MNAR_0
loading data
tpot2_imputetest/Impute_Experiments/data/6_True.pkl
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-17 15:47:00,971] A new study created in memory with name: no-name-97c3a824-7f2f-4c30-8022-ed9f9eecbb86
[W 2023-11-17 15:47:00,973] Trial 0 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:00,976] Trial 2 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:00,979] Trial 2 failed with value None.
[W 2023-11-17 15:47:00,977] Trial 1 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:01,182] Trial 1 failed with value None.
[W 2023-11-17 15:47:00,978] Trial 0 failed with value None.
[W 2023-11-17 15:47:00,978] Trial 3 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:01,561] Trial 3 failed with value None.
[W 2023-11-17 15:47:01,328] Trial 4 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:01,724] Trial 4 failed with value None.
[W 2023-11-17 15:47:01,329] Trial 6 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:01,872] Trial 6 failed with value None.
[W 2023-11-17 15:47:01,328] Trial 5 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:02,020] Trial 5 failed with value None.
[W 2023-11-17 15:47:01,723] Trial 10 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:02,166] Trial 10 failed with value None.
[W 2023-11-17 15:47:01,724] Trial 11 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:02,312] Trial 11 failed with value None.
[W 2023-11-17 15:47:01,330] Trial 8 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:02,458] Trial 8 failed with value None.
[W 2023-11-17 15:47:02,018] Trial 13 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:02,605] Trial 13 failed with value None.
[W 2023-11-17 15:47:01,329] Trial 7 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:02,754] Trial 7 failed with value None.
[W 2023-11-17 15:47:02,311] Trial 15 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:02,900] Trial 15 failed with value None.
[W 2023-11-17 15:47:01,869] Trial 12 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,046] Trial 12 failed with value None.
[W 2023-11-17 15:47:02,601] Trial 17 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,194] Trial 17 failed with value None.
[W 2023-11-17 15:47:01,721] Trial 9 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,346] Trial 9 failed with value None.
[W 2023-11-17 15:47:02,751] Trial 20 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,490] Trial 20 failed with value None.
[W 2023-11-17 15:47:02,754] Trial 22 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,634] Trial 22 failed with value None.
[W 2023-11-17 15:47:02,900] Trial 23 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,782] Trial 23 failed with value None.
[W 2023-11-17 15:47:03,046] Trial 24 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,929] Trial 24 failed with value None.
[W 2023-11-17 15:47:03,192] Trial 25 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,077] Trial 25 failed with value None.
[W 2023-11-17 15:47:02,604] Trial 19 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,226] Trial 19 failed with value None.
[W 2023-11-17 15:47:03,345] Trial 28 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,371] Trial 28 failed with value None.
[W 2023-11-17 15:47:02,312] Trial 16 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,515] Trial 16 failed with value None.
[W 2023-11-17 15:47:03,634] Trial 30 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,659] Trial 30 failed with value None.
[W 2023-11-17 15:47:03,780] Trial 32 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,807] Trial 32 failed with value None.
[W 2023-11-17 15:47:02,602] Trial 18 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,954] Trial 18 failed with value None.
[W 2023-11-17 15:47:03,928] Trial 34 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:05,099] Trial 34 failed with value None.
[W 2023-11-17 15:47:03,343] Trial 27 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:05,245] Trial 27 failed with value None.
[W 2023-11-17 15:47:04,225] Trial 36 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:05,389] Trial 36 failed with value None.
[W 2023-11-17 15:47:04,370] Trial 37 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:05,534] Trial 37 failed with value None.
[W 2023-11-17 15:47:03,490] Trial 29 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:05,682] Trial 29 failed with value None.
[W 2023-11-17 15:47:02,020] Trial 14 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:04,806] Trial 40 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:05,829] Trial 40 failed with value None.
[W 2023-11-17 15:47:03,782] Trial 33 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:05,975] Trial 33 failed with value None.
[W 2023-11-17 15:47:05,099] Trial 41 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,121] Trial 41 failed with value None.
[W 2023-11-17 15:47:02,752] Trial 21 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,264] Trial 21 failed with value None.
[W 2023-11-17 15:47:04,371] Trial 38 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,409] Trial 38 failed with value None.
[W 2023-11-17 15:47:04,514] Trial 39 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,554] Trial 39 failed with value None.
[W 2023-11-17 15:47:05,682] Trial 45 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,698] Trial 45 failed with value None.
[W 2023-11-17 15:47:05,828] Trial 46 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:03,193] Trial 26 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,845] Trial 26 failed with value None.
[W 2023-11-17 15:47:04,224] Trial 35 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,990] Trial 35 failed with value None.
[W 2023-11-17 15:47:05,534] Trial 43 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:07,133] Trial 43 failed with value None.
[W 2023-11-17 15:47:03,779] Trial 31 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:06,844] Trial 47 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:07,278] Trial 47 failed with value None.
[W 2023-11-17 15:47:06,845] Trial 46 failed with value None.
[W 2023-11-17 15:47:05,682] Trial 44 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:07,653] Trial 44 failed with value None.
[W 2023-11-17 15:47:05,828] Trial 14 failed with value None.
[W 2023-11-17 15:47:05,389] Trial 42 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:47:07,278] Trial 31 failed with value None.
[W 2023-11-17 15:47:08,044] Trial 42 failed with value None.
failed on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_normal_6_0.1_MNAR_0
module 'utils' has no attribute 'trial_suggestion'
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 169, in loop_through_tasks
    SimpleImputeSpace.fit(X_train_pandas)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'

DONE
