/cm/local/apps/slurm/var/spool/job402233/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job402233/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job402233/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-21 09:45:59.500235: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-21 09:45:59.536709: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-21 09:45:59.536736: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-21 09:45:59.538136: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-21 09:45:59.544599: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-21 09:46:15.101140: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
working on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.3_MAR_0
loading data
tpot2_imputetest/Impute_Experiments/data/6_True.pkl
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-21 09:47:31,417] A new study created in memory with name: no-name-ac1a6c69-cfd0-4300-9472-fb8f97606bc4
[W 2023-11-21 09:47:31,420] Trial 0 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:31,428] Trial 0 failed with value None.
[W 2023-11-21 09:47:31,421] Trial 1 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:31,607] Trial 1 failed with value None.
[W 2023-11-21 09:47:31,422] Trial 3 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:31,752] Trial 3 failed with value None.
[W 2023-11-21 09:47:31,424] Trial 5 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:31,895] Trial 5 failed with value None.
[W 2023-11-21 09:47:31,426] Trial 8 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:32,038] Trial 8 failed with value None.
[W 2023-11-21 09:47:31,428] Trial 9 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:32,178] Trial 9 failed with value None.
[W 2023-11-21 09:47:31,748] Trial 10 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:32,318] Trial 10 failed with value None.
[W 2023-11-21 09:47:31,751] Trial 12 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:32,467] Trial 12 failed with value None.
[W 2023-11-21 09:47:31,893] Trial 13 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:32,612] Trial 13 failed with value None.
[W 2023-11-21 09:47:31,895] Trial 14 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:32,753] Trial 14 failed with value None.
[W 2023-11-21 09:47:32,038] Trial 15 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:32,892] Trial 15 failed with value None.
[W 2023-11-21 09:47:32,318] Trial 16 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,034] Trial 16 failed with value None.
[W 2023-11-21 09:47:32,319] Trial 17 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,181] Trial 17 failed with value None.
[W 2023-11-21 09:47:32,463] Trial 18 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,324] Trial 18 failed with value None.
[W 2023-11-21 09:47:32,464] Trial 20 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,465] Trial 20 failed with value None.
[W 2023-11-21 09:47:31,425] Trial 6 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,606] Trial 6 failed with value None.
[W 2023-11-21 09:47:31,422] Trial 2 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,749] Trial 2 failed with value None.
[W 2023-11-21 09:47:31,749] Trial 11 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,891] Trial 11 failed with value None.
[W 2023-11-21 09:47:33,176] Trial 23 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:33,180] Trial 25 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:34,032] Trial 25 failed with value None.
[W 2023-11-21 09:47:33,324] Trial 26 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:34,176] Trial 26 failed with value None.
[W 2023-11-21 09:47:32,466] Trial 21 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:34,316] Trial 21 failed with value None.
[W 2023-11-21 09:47:33,605] Trial 27 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:34,461] Trial 27 failed with value None.
[W 2023-11-21 09:47:33,747] Trial 28 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:34,603] Trial 28 failed with value None.
[W 2023-11-21 09:47:33,177] Trial 24 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:34,746] Trial 24 failed with value None.
[W 2023-11-21 09:47:32,464] Trial 19 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:34,888] Trial 19 failed with value None.
[W 2023-11-21 09:47:31,423] Trial 4 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:35,029] Trial 4 failed with value None.
[W 2023-11-21 09:47:34,601] Trial 30 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:35,172] Trial 30 failed with value None.
[W 2023-11-21 09:47:34,602] Trial 31 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:35,314] Trial 31 failed with value None.
[W 2023-11-21 09:47:31,425] Trial 7 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:35,454] Trial 7 failed with value None.
[W 2023-11-21 09:47:33,033] Trial 22 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:35,594] Trial 22 failed with value None.
[W 2023-11-21 09:47:35,313] Trial 33 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:35,737] Trial 33 failed with value None.
[W 2023-11-21 09:47:34,315] Trial 29 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:35,877] Trial 29 failed with value None.
[W 2023-11-21 09:47:34,032] Trial 23 failed with value None.
[W 2023-11-21 09:47:35,737] Trial 35 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:36,162] Trial 35 failed with value None.
[W 2023-11-21 09:47:35,170] Trial 32 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:36,303] Trial 32 failed with value None.
[W 2023-11-21 09:47:36,161] Trial 36 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:36,442] Trial 36 failed with value None.
[W 2023-11-21 09:47:35,737] Trial 34 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:36,583] Trial 34 failed with value None.
[W 2023-11-21 09:47:36,302] Trial 39 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:36,725] Trial 39 failed with value None.
[W 2023-11-21 09:47:36,303] Trial 41 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:36,865] Trial 41 failed with value None.
[W 2023-11-21 09:47:36,302] Trial 38 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,004] Trial 38 failed with value None.
[W 2023-11-21 09:47:36,303] Trial 40 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,146] Trial 40 failed with value None.
[W 2023-11-21 09:47:36,724] Trial 44 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,288] Trial 44 failed with value None.
[W 2023-11-21 09:47:36,162] Trial 37 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,431] Trial 37 failed with value None.
[W 2023-11-21 09:47:36,724] Trial 43 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,572] Trial 43 failed with value None.
[W 2023-11-21 09:47:37,146] Trial 47 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,714] Trial 47 failed with value None.
[W 2023-11-21 09:47:36,865] Trial 46 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,857] Trial 46 failed with value None.
[W 2023-11-21 09:47:36,725] Trial 45 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:37,997] Trial 45 failed with value None.
[W 2023-11-21 09:47:36,583] Trial 42 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'random_state'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
[W 2023-11-21 09:47:38,138] Trial 42 failed with value None.
failed on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.3_MAR_0
SimpleImputer.__init__() got an unexpected keyword argument 'random_state'
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 169, in loop_through_tasks
    SimpleImputeSpace.fit(X_train_pandas)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 60, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'random_state'

DONE
