/cm/local/apps/slurm/var/spool/job402248/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job402248/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job402248/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-21 09:49:46.903909: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-21 09:49:46.938576: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-21 09:49:46.938602: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-21 09:49:46.939739: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-21 09:49:46.945288: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-21 09:49:49.598221: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
working on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_normal_6_0.5_MAR_0
loading data
tpot2_imputetest/Impute_Experiments/data/6_True.pkl
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-21 09:50:51,101] A new study created in memory with name: no-name-5c0206d8-5afc-4f12-9950-e6107bfd11b6
[W 2023-11-21 09:50:51,103] Trial 0 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:51,114] Trial 0 failed with value None.
[W 2023-11-21 09:50:51,105] Trial 1 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:51,395] Trial 1 failed with value None.
[W 2023-11-21 09:50:51,106] Trial 3 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:51,567] Trial 3 failed with value None.
[W 2023-11-21 09:50:51,109] Trial 6 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:51,729] Trial 6 failed with value None.
[W 2023-11-21 09:50:51,111] Trial 7 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:51,886] Trial 7 failed with value None.
[W 2023-11-21 09:50:51,113] Trial 9 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,045] Trial 9 failed with value None.
[W 2023-11-21 09:50:51,106] Trial 2 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,205] Trial 2 failed with value None.
[W 2023-11-21 09:50:51,395] Trial 12 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,362] Trial 12 failed with value None.
[W 2023-11-21 09:50:51,109] Trial 5 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,576] Trial 5 failed with value None.
[W 2023-11-21 09:50:51,112] Trial 8 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,756] Trial 8 failed with value None.
[W 2023-11-21 09:50:52,044] Trial 14 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,917] Trial 14 failed with value None.
[W 2023-11-21 09:50:52,204] Trial 16 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:53,085] Trial 16 failed with value None.
[W 2023-11-21 09:50:52,204] Trial 17 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:53,246] Trial 17 failed with value None.
[W 2023-11-21 09:50:52,360] Trial 18 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:53,407] Trial 18 failed with value None.
[W 2023-11-21 09:50:51,728] Trial 13 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:53,570] Trial 13 failed with value None.
[W 2023-11-21 09:50:52,751] Trial 21 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:53,728] Trial 21 failed with value None.
[W 2023-11-21 09:50:52,752] Trial 22 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,754] Trial 24 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:52,755] Trial 25 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:53,949] Trial 25 failed with value None.
[W 2023-11-21 09:50:51,393] Trial 11 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:54,122] Trial 11 failed with value None.
[W 2023-11-21 09:50:51,107] Trial 4 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:54,289] Trial 4 failed with value None.
[W 2023-11-21 09:50:53,244] Trial 27 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:54,451] Trial 27 failed with value None.
[W 2023-11-21 09:50:52,362] Trial 19 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:54,611] Trial 19 failed with value None.
[W 2023-11-21 09:50:51,113] Trial 10 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:54,770] Trial 10 failed with value None.
[W 2023-11-21 09:50:52,753] Trial 23 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:54,934] Trial 23 failed with value None.
[W 2023-11-21 09:50:53,945] Trial 22 failed with value None.
[W 2023-11-21 09:50:53,947] Trial 32 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:55,253] Trial 32 failed with value None.
[W 2023-11-21 09:50:53,948] Trial 33 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:55,415] Trial 33 failed with value None.
[W 2023-11-21 09:50:52,045] Trial 15 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:55,577] Trial 15 failed with value None.
[W 2023-11-21 09:50:54,286] Trial 34 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:54,287] Trial 36 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:55,738] Trial 36 failed with value None.
[W 2023-11-21 09:50:54,288] Trial 37 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:55,902] Trial 37 failed with value None.
[W 2023-11-21 09:50:53,405] Trial 29 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:56,061] Trial 29 failed with value None.
[W 2023-11-21 09:50:52,750] Trial 20 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:56,220] Trial 20 failed with value None.
[W 2023-11-21 09:50:53,946] Trial 31 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:56,382] Trial 31 failed with value None.
[W 2023-11-21 09:50:55,093] Trial 40 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:56,545] Trial 40 failed with value None.
[W 2023-11-21 09:50:54,286] Trial 35 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:56,707] Trial 35 failed with value None.
[W 2023-11-21 09:50:55,737] Trial 34 failed with value None.
[W 2023-11-21 09:50:55,738] Trial 42 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:57,027] Trial 42 failed with value None.
[W 2023-11-21 09:50:53,246] Trial 28 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:57,185] Trial 28 failed with value None.
[W 2023-11-21 09:50:55,902] Trial 44 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:57,345] Trial 44 failed with value None.
[W 2023-11-21 09:50:54,933] Trial 38 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:57,504] Trial 38 failed with value None.
[W 2023-11-21 09:50:56,382] Trial 45 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:57,663] Trial 45 failed with value None.
[W 2023-11-21 09:50:56,545] Trial 46 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:57,821] Trial 46 failed with value None.
[W 2023-11-21 09:50:55,737] Trial 41 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:57,981] Trial 41 failed with value None.
[W 2023-11-21 09:50:55,901] Trial 43 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:58,138] Trial 43 failed with value None.
[W 2023-11-21 09:50:53,949] Trial 24 failed with value None.
[W 2023-11-21 09:50:53,084] Trial 26 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:58,531] Trial 26 failed with value None.
[W 2023-11-21 09:50:56,708] Trial 47 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:58,693] Trial 47 failed with value None.
[W 2023-11-21 09:50:54,934] Trial 39 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:58,856] Trial 39 failed with value None.
[W 2023-11-21 09:50:53,569] Trial 30 failed with parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'} because of the following error: TypeError("SimpleImputer.__init__() got an unexpected keyword argument 'model_name'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
[W 2023-11-21 09:50:59,016] Trial 30 failed with value None.
failed on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_normal_6_0.5_MAR_0
SimpleImputer.__init__() got an unexpected keyword argument 'model_name'
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 169, in loop_through_tasks
    SimpleImputeSpace.fit(X_train_pandas)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 60, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 57, in obj
    my_model = autoutils.MyModel(random_state = self.random_state, **my_params)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 35, in MyModel
    my_model = SimpleImputer(
TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'model_name'

DONE
