/cm/local/apps/slurm/var/spool/job379088/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job379088/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job379088/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-17 15:46:23.332843: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-17 15:46:23.366960: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-17 15:46:23.366986: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-17 15:46:23.367877: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-17 15:46:23.373096: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-17 15:46:24.572676: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
working on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.01_MAR_0
loading data
tpot2_imputetest/Impute_Experiments/data/6_True.pkl
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-17 15:46:37,862] A new study created in memory with name: no-name-b82ffb95-9028-4386-8a0d-e166ece0e12f
[W 2023-11-17 15:46:37,865] Trial 0 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:37,870] Trial 0 failed with value None.
[W 2023-11-17 15:46:37,866] Trial 1 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:38,026] Trial 1 failed with value None.
[W 2023-11-17 15:46:37,868] Trial 3 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:38,172] Trial 3 failed with value None.
[W 2023-11-17 15:46:37,870] Trial 5 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:38,314] Trial 5 failed with value None.
[W 2023-11-17 15:46:37,868] Trial 4 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:38,454] Trial 4 failed with value None.
[W 2023-11-17 15:46:38,170] Trial 7 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:38,596] Trial 7 failed with value None.
[W 2023-11-17 15:46:38,171] Trial 9 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:38,738] Trial 9 failed with value None.
[W 2023-11-17 15:46:38,172] Trial 11 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:38,880] Trial 11 failed with value None.
[W 2023-11-17 15:46:38,170] Trial 8 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,026] Trial 8 failed with value None.
[W 2023-11-17 15:46:38,596] Trial 12 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,172] Trial 12 failed with value None.
[W 2023-11-17 15:46:38,737] Trial 13 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,314] Trial 13 failed with value None.
[W 2023-11-17 15:46:38,738] Trial 15 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,457] Trial 15 failed with value None.
[W 2023-11-17 15:46:38,169] Trial 6 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,600] Trial 6 failed with value None.
[W 2023-11-17 15:46:38,171] Trial 10 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,742] Trial 10 failed with value None.
[W 2023-11-17 15:46:39,167] Trial 18 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,884] Trial 18 failed with value None.
[W 2023-11-17 15:46:39,170] Trial 21 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,027] Trial 21 failed with value None.
[W 2023-11-17 15:46:39,171] Trial 22 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,166] Trial 22 failed with value None.
[W 2023-11-17 15:46:39,314] Trial 23 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,311] Trial 23 failed with value None.
[W 2023-11-17 15:46:39,456] Trial 24 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,455] Trial 24 failed with value None.
[W 2023-11-17 15:46:39,597] Trial 25 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:39,599] Trial 27 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,599] Trial 27 failed with value None.
[W 2023-11-17 15:46:39,025] Trial 17 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,739] Trial 17 failed with value None.
[W 2023-11-17 15:46:39,742] Trial 29 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,881] Trial 29 failed with value None.
[W 2023-11-17 15:46:39,884] Trial 31 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:41,022] Trial 31 failed with value None.
[W 2023-11-17 15:46:39,169] Trial 20 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:41,161] Trial 20 failed with value None.
[W 2023-11-17 15:46:40,025] Trial 34 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:41,303] Trial 34 failed with value None.
[W 2023-11-17 15:46:40,026] Trial 35 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:41,442] Trial 35 failed with value None.
[W 2023-11-17 15:46:37,867] Trial 2 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:41,583] Trial 2 failed with value None.
[W 2023-11-17 15:46:40,308] Trial 37 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:41,723] Trial 37 failed with value None.
[W 2023-11-17 15:46:40,309] Trial 39 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:41,864] Trial 39 failed with value None.
[W 2023-11-17 15:46:39,023] Trial 16 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,004] Trial 16 failed with value None.
[W 2023-11-17 15:46:40,596] Trial 41 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,147] Trial 41 failed with value None.
[W 2023-11-17 15:46:40,599] Trial 42 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,288] Trial 42 failed with value None.
[W 2023-11-17 15:46:40,739] Trial 43 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,431] Trial 43 failed with value None.
[W 2023-11-17 15:46:39,883] Trial 30 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:40,025] Trial 33 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,573] Trial 33 failed with value None.
[W 2023-11-17 15:46:38,737] Trial 14 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,713] Trial 14 failed with value None.
[W 2023-11-17 15:46:41,582] Trial 44 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,853] Trial 44 failed with value None.
[W 2023-11-17 15:46:40,311] Trial 40 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:42,992] Trial 40 failed with value None.
[W 2023-11-17 15:46:39,598] Trial 26 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:43,133] Trial 26 failed with value None.
[W 2023-11-17 15:46:40,598] Trial 25 failed with value None.
[W 2023-11-17 15:46:39,740] Trial 28 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:43,415] Trial 28 failed with value None.
[W 2023-11-17 15:46:39,168] Trial 19 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:43,554] Trial 19 failed with value None.
[W 2023-11-17 15:46:42,572] Trial 30 failed with value None.
[W 2023-11-17 15:46:40,309] Trial 38 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:43,835] Trial 38 failed with value None.
[W 2023-11-17 15:46:41,864] Trial 45 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:43,976] Trial 45 failed with value None.
[W 2023-11-17 15:46:42,147] Trial 47 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:44,118] Trial 47 failed with value None.
[W 2023-11-17 15:46:40,308] Trial 36 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:44,258] Trial 36 failed with value None.
[W 2023-11-17 15:46:40,023] Trial 32 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:44,400] Trial 32 failed with value None.
[W 2023-11-17 15:46:42,004] Trial 46 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:44,542] Trial 46 failed with value None.
failed on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.01_MAR_0
module 'utils' has no attribute 'trial_suggestion'
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 169, in loop_through_tasks
    SimpleImputeSpace.fit(X_train_pandas)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'

DONE
