/cm/local/apps/slurm/var/spool/job379071/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job379071/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job379071/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-17 15:43:50.386581: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-17 15:43:51.295982: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-17 15:43:51.296154: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-17 15:43:51.451866: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-17 15:43:51.775955: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-17 15:43:56.916098: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
working on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.01_MNAR_0
loading data
data/6_True.pkl
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-17 15:44:17,627] A new study created in memory with name: no-name-24766b1a-ab2f-4594-9197-40baceea44af
[W 2023-11-17 15:44:17,631] Trial 0 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:17,636] Trial 0 failed with value None.
[W 2023-11-17 15:44:17,631] Trial 1 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:17,834] Trial 1 failed with value None.
[W 2023-11-17 15:44:17,633] Trial 3 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:17,976] Trial 3 failed with value None.
[W 2023-11-17 15:44:17,635] Trial 6 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:18,119] Trial 6 failed with value None.
[W 2023-11-17 15:44:17,636] Trial 7 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:18,260] Trial 7 failed with value None.
[W 2023-11-17 15:44:17,634] Trial 4 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:18,403] Trial 4 failed with value None.
[W 2023-11-17 15:44:18,119] Trial 8 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:18,547] Trial 8 failed with value None.
[W 2023-11-17 15:44:18,259] Trial 9 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:18,689] Trial 9 failed with value None.
[W 2023-11-17 15:44:17,632] Trial 2 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:18,835] Trial 2 failed with value None.
[W 2023-11-17 15:44:17,634] Trial 5 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:18,979] Trial 5 failed with value None.
[W 2023-11-17 15:44:18,834] Trial 12 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:19,124] Trial 12 failed with value None.
[W 2023-11-17 15:44:18,835] Trial 13 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:19,267] Trial 13 failed with value None.
[W 2023-11-17 15:44:18,545] Trial 10 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:19,410] Trial 10 failed with value None.
[W 2023-11-17 15:44:18,831] Trial 11 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:19,553] Trial 11 failed with value None.
[W 2023-11-17 15:44:19,409] Trial 15 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:19,695] Trial 15 failed with value None.
[W 2023-11-17 15:44:19,410] Trial 17 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:19,837] Trial 17 failed with value None.
[W 2023-11-17 15:44:19,553] Trial 18 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:19,981] Trial 18 failed with value None.
[W 2023-11-17 15:44:19,694] Trial 19 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,127] Trial 19 failed with value None.
[W 2023-11-17 15:44:19,836] Trial 20 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,275] Trial 20 failed with value None.
[W 2023-11-17 15:44:19,981] Trial 21 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,418] Trial 21 failed with value None.
[W 2023-11-17 15:44:20,125] Trial 22 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,561] Trial 22 failed with value None.
[W 2023-11-17 15:44:20,272] Trial 24 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,706] Trial 24 failed with value None.
[W 2023-11-17 15:44:20,274] Trial 25 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,850] Trial 25 failed with value None.
[W 2023-11-17 15:44:20,127] Trial 23 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,993] Trial 23 failed with value None.
[W 2023-11-17 15:44:19,266] Trial 14 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:21,137] Trial 14 failed with value None.
[W 2023-11-17 15:44:20,703] Trial 28 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:21,278] Trial 28 failed with value None.
[W 2023-11-17 15:44:20,274] Trial 26 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:20,849] Trial 31 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:21,420] Trial 31 failed with value None.
[W 2023-11-17 15:44:19,410] Trial 16 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:21,562] Trial 16 failed with value None.
[W 2023-11-17 15:44:21,277] Trial 32 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:21,702] Trial 32 failed with value None.
[W 2023-11-17 15:44:20,848] Trial 30 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:21,844] Trial 30 failed with value None.
[W 2023-11-17 15:44:20,702] Trial 27 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:21,986] Trial 27 failed with value None.
[W 2023-11-17 15:44:20,704] Trial 29 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:22,126] Trial 29 failed with value None.
[W 2023-11-17 15:44:21,562] Trial 33 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:22,270] Trial 33 failed with value None.
[W 2023-11-17 15:44:21,420] Trial 26 failed with value None.
[W 2023-11-17 15:44:22,550] Trial 34 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:22,550] Trial 35 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:22,550] Trial 35 failed with value None.
[W 2023-11-17 15:44:22,550] Trial 34 failed with value None.
[W 2023-11-17 15:44:22,691] Trial 36 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:22,834] Trial 36 failed with value None.
[W 2023-11-17 15:44:22,834] Trial 37 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:22,976] Trial 37 failed with value None.
[W 2023-11-17 15:44:23,117] Trial 38 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:23,117] Trial 38 failed with value None.
[W 2023-11-17 15:44:23,260] Trial 39 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:23,260] Trial 39 failed with value None.
[W 2023-11-17 15:44:23,405] Trial 40 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:23,405] Trial 40 failed with value None.
[W 2023-11-17 15:44:23,547] Trial 41 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:23,548] Trial 41 failed with value None.
[W 2023-11-17 15:44:23,547] Trial 42 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:23,692] Trial 42 failed with value None.
[W 2023-11-17 15:44:23,835] Trial 43 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:23,835] Trial 43 failed with value None.
[W 2023-11-17 15:44:23,978] Trial 44 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:23,978] Trial 44 failed with value None.
[W 2023-11-17 15:44:24,120] Trial 45 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:24,120] Trial 45 failed with value None.
[W 2023-11-17 15:44:24,263] Trial 46 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:24,263] Trial 46 failed with value None.
[W 2023-11-17 15:44:24,404] Trial 47 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:44:24,404] Trial 47 failed with value None.
failed on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.01_MNAR_0
module 'utils' has no attribute 'trial_suggestion'
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 169, in loop_through_tasks
    SimpleImputeSpace.fit(X_train_pandas)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'

DONE
