/cm/local/apps/slurm/var/spool/job379086/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job379086/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job379086/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-17 15:46:22.993999: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-17 15:46:23.028629: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-17 15:46:23.028655: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-17 15:46:23.029762: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-17 15:46:23.035949: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-17 15:46:24.164680: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
working on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.1_MCAR_0
loading data
tpot2_imputetest/Impute_Experiments/data/6_True.pkl
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-17 15:46:46,466] A new study created in memory with name: no-name-459f257a-ebdd-475e-ae30-fbff6011f521
[W 2023-11-17 15:46:46,467] Trial 0 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:46,469] Trial 0 failed with value None.
[W 2023-11-17 15:46:46,468] Trial 1 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:46,620] Trial 1 failed with value None.
[W 2023-11-17 15:46:46,469] Trial 2 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:46,764] Trial 2 failed with value None.
[W 2023-11-17 15:46:46,763] Trial 3 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:46,906] Trial 3 failed with value None.
[W 2023-11-17 15:46:46,905] Trial 4 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:47,049] Trial 4 failed with value None.
[W 2023-11-17 15:46:47,046] Trial 5 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:47,189] Trial 5 failed with value None.
[W 2023-11-17 15:46:47,048] Trial 6 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:47,331] Trial 6 failed with value None.
[W 2023-11-17 15:46:47,189] Trial 8 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:47,471] Trial 8 failed with value None.
[W 2023-11-17 15:46:47,049] Trial 7 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:47,612] Trial 7 failed with value None.
[W 2023-11-17 15:46:47,753] Trial 9 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:47,753] Trial 9 failed with value None.
[W 2023-11-17 15:46:47,892] Trial 10 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:47,894] Trial 10 failed with value None.
[W 2023-11-17 15:46:48,036] Trial 11 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:48,037] Trial 11 failed with value None.
[W 2023-11-17 15:46:48,177] Trial 12 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:48,179] Trial 12 failed with value None.
[W 2023-11-17 15:46:48,179] Trial 13 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:48,326] Trial 13 failed with value None.
[W 2023-11-17 15:46:48,321] Trial 15 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:48,467] Trial 15 failed with value None.
[W 2023-11-17 15:46:48,323] Trial 17 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:48,608] Trial 17 failed with value None.
[W 2023-11-17 15:46:48,325] Trial 19 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:48,752] Trial 19 failed with value None.
[W 2023-11-17 15:46:48,320] Trial 14 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:48,892] Trial 14 failed with value None.
[W 2023-11-17 15:46:48,607] Trial 21 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:49,037] Trial 21 failed with value None.
[W 2023-11-17 15:46:48,607] Trial 22 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:49,180] Trial 22 failed with value None.
[W 2023-11-17 15:46:48,750] Trial 23 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:49,321] Trial 23 failed with value None.
[W 2023-11-17 15:46:48,467] Trial 20 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:49,461] Trial 20 failed with value None.
[W 2023-11-17 15:46:49,035] Trial 25 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:49,603] Trial 25 failed with value None.
[W 2023-11-17 15:46:48,324] Trial 18 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:49,746] Trial 18 failed with value None.
[W 2023-11-17 15:46:49,180] Trial 29 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:49,889] Trial 29 failed with value None.
[W 2023-11-17 15:46:48,751] Trial 24 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:50,031] Trial 24 failed with value None.
[W 2023-11-17 15:46:49,036] Trial 26 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:50,171] Trial 26 failed with value None.
[W 2023-11-17 15:46:49,746] Trial 30 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:50,313] Trial 30 failed with value None.
[W 2023-11-17 15:46:49,886] Trial 31 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:50,453] Trial 31 failed with value None.
[W 2023-11-17 15:46:48,322] Trial 16 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:50,594] Trial 16 failed with value None.
[W 2023-11-17 15:46:50,171] Trial 33 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:50,737] Trial 33 failed with value None.
[W 2023-11-17 15:46:49,888] Trial 32 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:50,877] Trial 32 failed with value None.
[W 2023-11-17 15:46:50,594] Trial 34 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:51,018] Trial 34 failed with value None.
[W 2023-11-17 15:46:49,178] Trial 28 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:51,159] Trial 28 failed with value None.
[W 2023-11-17 15:46:50,594] Trial 35 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:51,301] Trial 35 failed with value None.
[W 2023-11-17 15:46:49,037] Trial 27 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:51,443] Trial 27 failed with value None.
[W 2023-11-17 15:46:51,017] Trial 36 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:51,585] Trial 36 failed with value None.
[W 2023-11-17 15:46:51,724] Trial 37 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:51,724] Trial 37 failed with value None.
[W 2023-11-17 15:46:51,868] Trial 38 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:51,869] Trial 38 failed with value None.
[W 2023-11-17 15:46:52,009] Trial 39 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,009] Trial 39 failed with value None.
[W 2023-11-17 15:46:52,009] Trial 40 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,150] Trial 40 failed with value None.
[W 2023-11-17 15:46:52,290] Trial 41 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,290] Trial 41 failed with value None.
[W 2023-11-17 15:46:52,432] Trial 42 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,433] Trial 42 failed with value None.
[W 2023-11-17 15:46:52,574] Trial 43 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,574] Trial 43 failed with value None.
[W 2023-11-17 15:46:52,713] Trial 44 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,714] Trial 44 failed with value None.
[W 2023-11-17 15:46:52,855] Trial 45 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,855] Trial 45 failed with value None.
[W 2023-11-17 15:46:52,995] Trial 46 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:52,996] Trial 46 failed with value None.
[W 2023-11-17 15:46:53,138] Trial 47 failed with parameters: {} because of the following error: AttributeError("module 'utils' has no attribute 'trial_suggestion'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'
[W 2023-11-17 15:46:53,138] Trial 47 failed with value None.
failed on 
tpot2_imputetest/Impute_Experiments/logs//tpot2_base_imputation_6_0.1_MCAR_0
module 'utils' has no attribute 'trial_suggestion'
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 169, in loop_through_tasks
    SimpleImputeSpace.fit(X_train_pandas)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 55, in obj
    my_params = utils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: module 'utils' has no attribute 'trial_suggestion'

DONE
