Run: 10
/cm/local/apps/slurm/var/spool/job565585/slurm_script: line 23: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job565585/slurm_script: line 26: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job565585/slurm_script: line 31: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-12-19 13:22:16.090533: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-19 13:22:16.125034: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-19 13:22:16.125057: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-19 13:22:16.126179: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-19 13:22:16.131737: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-19 13:22:17.247037: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
starting loops
working on 
logs/6/tpot2_base_normal_MAR_0.9
2.582639694213867
loading data
logs/6/tpot2_base_normal_MAR_0.9/data/6_True.pkl
working on 
logs/6/tpot2_base_imputation_MAR_0.9
4.867365121841431
loading data
logs/6/tpot2_base_imputation_MAR_0.9/data/6_True.pkl
6
finished
working on 
logs/26/tpot2_base_normal_MAR_0.9
1.6996586322784424
loading data
logs/26/tpot2_base_normal_MAR_0.9/data/26_True.pkl
working on 
logs/26/tpot2_base_imputation_MAR_0.9
1.7495214939117432
loading data
logs/26/tpot2_base_imputation_MAR_0.9/data/26_True.pkl
26
finished
working on 
logs/30/tpot2_base_normal_MAR_0.9
0.762091875076294
loading data
logs/30/tpot2_base_normal_MAR_0.9/data/30_True.pkl
working on 
logs/30/tpot2_base_imputation_MAR_0.9
4.32625150680542
loading data
logs/30/tpot2_base_imputation_MAR_0.9/data/30_True.pkl
30
finished
working on 
logs/32/tpot2_base_normal_MAR_0.9
3.566713809967041
loading data
logs/32/tpot2_base_normal_MAR_0.9/data/32_True.pkl
working on 
logs/32/tpot2_base_imputation_MAR_0.9
0.35768651962280273
loading data
logs/32/tpot2_base_imputation_MAR_0.9/data/32_True.pkl
32
finished
working on 
logs/137/tpot2_base_normal_MAR_0.9
1.6424956321716309
loading data
logs/137/tpot2_base_normal_MAR_0.9/data/137_True.pkl
failed on 
logs/137/tpot2_base_normal_MAR_0.9
[Errno 5] Input/output error: '/home/ketrong/.cache/openml/org/openml/www/datasets/75/qualities.xml'
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/openml/datasets/functions.py", line 1241, in _get_dataset_qualities_file
    with io.open(qualities_file, encoding="utf8") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ketrong/.cache/openml/org/openml/www/datasets/75/qualities.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 310, in loop_through_tasks
    X_train, y_train, X_test, y_test = load_task(base_save_folder=base_save_folder, exp=exp, type=type, levelstr=levelstr, task_id=taskid, preprocess=True)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/utils.py", line 200, in load_task
    task = openml.tasks.get_task(task_id, **kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/openml/tasks/functions.py", line 415, in get_task
    raise e
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/openml/tasks/functions.py", line 399, in get_task
    dataset = get_dataset(task.dataset_id, *dataset_args, **get_dataset_kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/openml/datasets/functions.py", line 493, in get_dataset
    qualities_file = _get_dataset_qualities_file(did_cache_dir, dataset_id)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/openml/datasets/functions.py", line 1246, in _get_dataset_qualities_file
    with io.open(qualities_file, "w", encoding="utf8") as fh:
OSError: [Errno 5] Input/output error: '/home/ketrong/.cache/openml/org/openml/www/datasets/75/qualities.xml'

full run takes
0.018383026586638557
hours
DONE
